baseurl = "https://reside-ic.github.io/"
theme = "cocoa-eh"
builddrafts = true
canonifyurls = true
contentdir = "content"
languageCode = "en-US"
layoutdir = "layouts"
publishdir = "public"
title = "Reside-IC"
disqusshortname = ""
pluralizelisttitles = false
disqusShortname = "reside-ic"

[permalinks]
blog = "blog/:slug/"

[params]
share = true
share_on_googleplus = false
dateform = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description = "Research software for infectious disease epidemiology at Imperial College"
copyright = "Copyright Â© 2019 Reside-IC"
logofile = "img/logo.png"
faviconfile = "img/logo.png"
highlightjs = true
progressively = true
align_left = false
lang = "en"
github = "reside-ic"
posts_navigation = true
small_banner_logo = false
latestpostcount = 5
